### ISSUE TITLE
How to load color-stylesheet.twig to add a logo to skosmos

### ISSUE THREAD

**Issue by LYNCETECH** [NatLibFi/Skosmos#629]
I tried to add a logo to skosmos but it was not inserted. I searched where is the color-stylesheet.twig file inserted into the application but I have not found it. Will I know what to do to insert a logo correctly? I tried to modify the config.inc file but nothing.

**Comment by osma** [comment]
The `color-stylesheet.twig` template is actually not used anymore and should be removed from the code base.

If you want to insert a logo, you should write a custom stylesheet that specifies where and how the logo should be places, and point to its (relative) URL in the `CUSTOM_CSS` setting in `config.inc`.

For an example, see the [Finto custom stylesheet](http://finto.fi/resource/css/finto.css), in particular these rules:
```css
.service-fi h1, .service-sv h1, .service-en h1, #service-name {
  text-indent: -100%;
  white-space: nowrap;
  overflow: hidden;
}

.service-fi, .service-sv, .service-en {
  display: inline-block;
  background-repeat: no-repeat;
  height: 50px;
}

.service-fi {
  background-image: url('../finto-pics/tunnus-fi.gif');
  width: 505px;
}

.service-sv {
  background-image: url('../finto-pics/tunnus-sv.gif');
  width: 455px;
}

.service-en {
  background-image: url('../finto-pics/tunnus-en.gif');
  width: 465px;
}
```
